# Generated by Django 3.1.3 on 2020-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dylan_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('url_link', models.CharField(max_length=255)),
                ('svg_image', models.TextField()),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
