# Generated by Django 3.1.3 on 2020-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dylan_portfolio', '0002_navbaritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='shared/')),
                ('is_shared', models.BooleanField()),
            ],
        ),
    ]
